import hashlib
from random import randint, choice as rc
from faker import Faker

from app import app
from models import db, User, Chef, Recipe

if __name__ == '__main__':
    fake = Faker()

    with app.app_context():
        Chef.query.delete()

        users = []
        user1=User(name='Roberto', email='CEO@bobsburgers.com', password_hash=hashlib.sha256(b"hello1").hexdigest())
        users.append(user1)
        user2=User(name='John', email='john@applebees.com', password_hash=hashlib.sha256(b"orangessuck").hexdigest())
        users.append(user2)
        user3=User(name='diana', email='diana', password_hash=hashlib.sha256(b"12345").hexdigest())
        users.append(user3)
        user4=User(name='GordonRamsay', email='gordon@meditating.com', password_hash=hashlib.sha256(b"meditatingsux").hexdigest())
        users.append(user4)
        user5=User(name='Antonio', email='tony@bourdain.com', password_hash=hashlib.sha256(b"imstillhere").hexdigest())
        users.append(user5)
        user6=User(name='Julia', email='CEO@applebees.com', password_hash=hashlib.sha256(b"aheadofthejohns").hexdigest())
        users.append(user6)
        user7=User(name='dianasbiggestfan', email='chef@michelin.com', password_hash=hashlib.sha256(b"dianarocks").hexdigest())
        users.append(user7)

        db.session.add_all(users)
        db.session.commit()

        chefs = []
        chef1 = Chef(name='Diana', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Born in China and raised in the United States, and having spent most of her 20s traveling, her style of cooking is a combination of American and just a little bit Chinese. She\'s also an avid baker who can whip up any pastry you\'d like, including the protein bars that she makes in bulk for herself. Expect her to come to your house with a dish of tomato pasta with curry sauce and lots of cumin, and if you\'re lucky you may even get to try some of her home-made dumplings! ')
        chef2 = Chef(name='Gordon', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Gordon was named after his name-sake because his mother\'s was pregnant with him when their family restaurant in Sicily was saved by Gordon Ramsay. This was famously shown on one of the episodes of "Kitchen Nightmares," and the team here at Fuber is always glad to go to Gordon\'s family home to be embraced by their warm hospitality. I think you\'d also love the hospitality that Gordon provides (he is truly nothing like the other Gordon!) and you\'ll be even more grateful to try him family recipes. Why go to Italy when Gordon can make you and 10 of your friends the best annelletti you have ever had followed by a warm cannoli?')
        chef3 = Chef(name='Joon', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Joon is a data scientist by day, and a sushi chef by night. Diana and Joon met through their love of food andd started this company together. Joon sources the best ingredients from the restaurant suppliers in the city and is never unwilling to drive far for fresh fish! He\'s also a regular at the Japanese restaurant in the city, and will always pick up the best Japanese snacks after for you.')
        chef4 = Chef(name='Tony', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Having grown up in Texas, Tony\'s standards for barbeque are incredibly high, which you\'ll know the moment you taste his brisket. He chugs beer and eats a lot of meat, and is also the funniest guy you\'ll ever meet (meat?)!')
        chef5 = Chef(name='Anika', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Anika is an Indian-American who grew up in a multicultural home -- Californian father and Indian mother, so she grew up going to farmers markets on weekends and on weekdays preparing fresh naan with her mother. Her cooking style is the same -- she will source the absolute freshest ingredients for an herby salad, and while the curry is stewing on the stove top, she\'ll share all the wild stories of her travels around the world. If you\'re lucky, you may even get to go to her home and eat naan fresh out of her clay tandoor oven!')
        chefs.append(chef1)
        chefs.append(chef2)
        chefs.append(chef3)
        chefs.append(chef4)
        chefs.append(chef5)
        db.session.add_all(chefs)
        db.session.commit()

        recipes = []
        recipe1 = Recipe(title='Peking Duck', image='https://ctl.s6img.com/society6/img/Mr1oAx8Mt4yhjFvw1nj56aU7Dv0/w_700/prints/~artwork/s6-original-art-uploads/society6/uploads/misc/b7828f4eedee42acbbf57dc53fd62d37/~~/know-your-dumplings4156958-prints.jpg?attempt=0', recipe='', chef_id=1)
        recipes.append(recipe1)
        recipe2 = Recipe(title='Beef Noodle Soup', image='', recipe='', chef_id=1)
        recipes.append(recipe2)
        recipe3 = Recipe(title='Xiao Long Bao', image='', recipe='', chef_id=1)
        recipes.append(recipe3)
        recipe4 = Recipe(title='Wonton Soup', image='', recipe='', chef_id=1)
        recipes.append(recipe4)
        recipe5 = Recipe(title='Banana Bread', image='', recipe='', chef_id=1)
        recipes.append(recipe5)
        recipe6 = Recipe(title='Stir Fry', image='', recipe='', chef_id=1)
        recipes.append(recipe6)
        recipe7 = Recipe(title='Napoletana Pizza', image='', recipe='', chef_id=2)
        recipes.append(recipe7)
        recipe8 = Recipe(title='Florentina Steak', image='', recipe='', chef_id=2)
        recipes.append(recipe8)
        recipe9 = Recipe(title='Risotto', image='', recipe='', chef_id=2)
        recipes.append(recipe9)
        recipe10 = Recipe(title='Gelato', image='', recipe='', chef_id=2)
        recipes.append(recipe10)
        recipe11 = Recipe(title='Spaghetti Carbonara', image='', recipe='', chef_id=2)
        recipes.append(recipe11)
        recipe12 = Recipe(title='Gnocchi', image='', recipe='', chef_id=2)
        recipes.append(recipe12)
        recipe13 = Recipe(title='Omakase', image='', recipe='', chef_id=3)
        recipes.append(recipe13)
        recipe14 = Recipe(title='Japanese desserts', image='', recipe='', chef_id=3)
        recipes.append(recipe14)
        recipe15 = Recipe(title='Tex Mex pizza', image='', recipe='', chef_id=4)
        recipes.append(recipe15)
        recipe16 = Recipe(title='Pecan Pie', image='https://assets.epicurious.com/photos/59bc16e71782591a4bc6659a/1:1/w_2240,c_limit/OLD-FASHIONED-PECAN-PIE-07092017.jpg', recipe='', chef_id=4)
        recipes.append(recipe16)
        recipe17 = Recipe(title='Texas bbq', image='https://www.2fiftybbq.com/uploads/b/8bc4665539db00db7b59e47adeb796c1b71244a870cde202dd6313a486bd19a3/IMG_0859-copy-2048x1366_1639132772.jpeg', recipe='', chef_id=4)
        recipes.append(recipe12)
        recipe18 = Recipe(title='', image='', recipe='', chef_id=4)
        recipes.append(recipe18)
        recipe19 = Recipe(title='', image='', recipe='', chef_id=4)
        recipes.append(recipe19)
        recipe20 = Recipe(title='', image='', recipe='', chef_id=4)
        recipes.append(recipe20)
        recipe21 = Recipe(title='Garlic Naan', image='https://rasamalaysia.com/wp-content/uploads/2019/03/naan3.jpg', recipe='', chef_id=5)
        recipes.append(recipe21)
        recipe22 = Recipe(title='Biryani', image='', recipe='', chef_id=5)
        recipes.append(recipe22)
        recipe23 = Recipe(title='https://glebekitchen.com/wp-content/uploads/2019/12/chickenbiryanibowltop.jpg', image='', recipe='', chef_id=5)
        recipes.append(recipe23)
        recipe24 = Recipe(title='Kalakand (Milk Cake)', image='https://myheartbeets.com/wp-content/uploads/2020/10/instant-pot-indian-dessert.jpg', recipe='', chef_id=5)
        recipes.append(recipe24)
        recipe25 = Recipe(title='Farmers Market Produce', image='https://images.squarespace-cdn.com/content/v1/54b3f75ee4b0cdf625ece0b0/1432664420994-70E6QFI6BCNEP9XAS88U/market+basket+FMC.JPG?format=1000w', recipe='', chef_id=5)
        recipes.append(recipe25)
        db.session.add_all(recipes)
        db.session.commit()

        # reviews = []
        # r1 = Review(user='', rating='', text='', chef_id=3, user_id=3)
        # db.session.add_all(reviews)
        # db.session.commit()