import hashlib
from random import randint, choice as rc
from faker import Faker

from app import app
from models import db, User, Chef, Recipe

if __name__ == '__main__':
    fake = Faker()

    with app.app_context():
        Chef.query.delete()

        users = []
        user1=User(name='Roberto', email='CEO@bobsburgers.com', password_hash=hashlib.sha256(b"hello1").hexdigest())
        users.append(user1)
        user2=User(name='John', email='john@applebees.com', password_hash=hashlib.sha256(b"orangessuck").hexdigest())
        users.append(user2)
        user3=User(name='diana', email='diana', password_hash=hashlib.sha256(b"12345").hexdigest())
        users.append(user3)
        user4=User(name='GordonRamsay', email='gordon@meditating.com', password_hash=hashlib.sha256(b"meditatingsux").hexdigest())
        users.append(user4)
        user5=User(name='Antonio', email='tony@bourdain.com', password_hash=hashlib.sha256(b"imstillhere").hexdigest())
        users.append(user5)
        user6=User(name='Julia', email='CEO@applebees.com', password_hash=hashlib.sha256(b"aheadofthejohns").hexdigest())
        users.append(user6)
        user7=User(name='dianasbiggestfan', email='chef@michelin.com', password_hash=hashlib.sha256(b"dianarocks").hexdigest())
        users.append(user7)

        db.session.add_all(users)
        db.session.commit()

        chefs = []
        chef1 = Chef(name='Diana', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Born in China and raised in the United States, and having spent most of her 20s traveling, her style of cooking is a combination of American and just a little bit Chinese. She\'s also an avid baker who can whip up any pastry you\'d like, including the protein bars that she makes in bulk for herself. Expect her to come to your house with a dish of tomato pasta with curry sauce and lots of cumin, and if you\'re lucky you may even get to try some of her home-made dumplings! ')
        chef2 = Chef(name='Gordon', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Gordon was named after his name-sake because his mother\'s was pregnant with him when their family restaurant in Sicily was saved by Gordon Ramsay. This was famously shown on one of the episodes of "Kitchen Nightmares," and the team here at Fuber is always glad to go to Gordon\'s family home to be embraced by their warm hospitality. I think you\'d also love the hospitality that Gordon provides (he is truly nothing like the other Gordon!) and you\'ll be even more grateful to try him family recipes. Why go to Italy when Gordon can make you and 10 of your friends the best annelletti you have ever had followed by a warm cannoli?')
        chef3 = Chef(name='Joon', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Joon is a data scientist by day, and a sushi chef by night. Diana and Joon met through their love of food andd started this company together. Joon sources the best ingredients from the restaurant suppliers in the city and is never unwilling to drive far for fresh fish! He\'s also a regular at the Japanese restaurant in the city, and will always pick up the best Japanese snacks after for you.')
        chef4 = Chef(name='Tony', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Having grown up in Texas, Tony\'s standards for barbeque are incredibly high, which you\'ll know the moment you taste his brisket. He chugs beer and eats a lot of meat, and is also the funniest guy you\'ll ever meet (meat?)!')
        chef5 = Chef(name='Anika', image='https://i.etsystatic.com/24621230/r/il/3ed751/4000472662/il_1588xN.4000472662_8jga.jpg', bio='Anika is an Indian-American who grew up in a multicultural home -- Californian father and Indian mother, so she grew up going to farmers markets on weekends and on weekdays preparing fresh naan with her mother. Her cooking style is the same -- she will source the absolute freshest ingredients for an herby salad, and while the curry is stewing on the stove top, she\'ll share all the wild stories of her travels around the world. If you\'re lucky, you may even get to go to her home and eat naan fresh out of her clay tandoor oven!')
        chefs.append(chef1)
        chefs.append(chef2)
        chefs.append(chef3)
        chefs.append(chef4)
        chefs.append(chef5)
        db.session.add_all(chefs)
        db.session.commit()

        recipes = []
        recipe1 = Recipe(title='Beef Noodle Soup', image='', description='Diana sources hand made soup noodles from Clement street (the real Chinatown of San Francisco) and slow cooks the beef for eight hours before serving it with flavorful broth. With an extra hour to spare, you can learn to make hand made noodles with her!', chef_id=1)
        recipes.append(recipe1)
        recipe2 = Recipe(title='Peking Duck', image='', description='Special recipe that needs to be ordered 48 hours in advance, but this crisp duck wrapped in warm buns is a Chinese specialty that will not disappoint!', chef_id=1)
        recipes.append(recipe2)
        recipe3 = Recipe(title='Xiao Long Bao', image='', description='Chinese soup dumplings -- what Diana\'s hometown of Shanghai is known for!', chef_id=1)
        recipes.append(recipe3)
        recipe4 = Recipe(title='Wonton Soup', image='', description='Wonton soup is such a versatile meal -- you can cool it down to eat on a summer day, or eat it straight out of the pot on a winter day. You can have it as a light soup for breakfast, or as your first dish at dinner. ', chef_id=1)
        recipes.append(recipe4)
        recipe5 = Recipe(title='Banana Bread', image='', description='Secret ingredient is... Love. Just kidding, it\'s sour cream.', chef_id=1)
        recipes.append(recipe5)
        recipe6 = Recipe(title='Stir Fry', image='', description='Nice and simple dish with a side of rice. Choose your favorite vegetables and protein and add in a flair of your own!', chef_id=1)
        recipes.append(recipe6)
        recipe7 = Recipe(title='Napoletana Pizza', image='', description='Gordon makes the dough himself at home 8 hours before he comes to your house, so that you can have the fluffiest pizza of your life. This is perfect for house parties! ', chef_id=2)
        recipes.append(recipe7)
        recipe8 = Recipe(title='Florentina Steak', image='', description='We all know how to cook steak, but do you know how to cook the PERFECT steak?', chef_id=2)
        recipes.append(recipe8)
        recipe9 = Recipe(title='Orzo Risotto', image='', description='Risotto is another one of those recipes that is so hard to master, but if you\'re in the mood for it, Gordon could show you step by step how he gets the creamiest risotto ever. He uses orzo instead of rice and now you have some leftover white wine to share for the meal!', chef_id=2)
        recipes.append(recipe9)
        recipe10 = Recipe(title='Gelato', image='', description='Gordon is probably one of the only people in San Francisco who has an extra freezer... just for gelato. Dessert is covered!', chef_id=2)
        recipes.append(recipe10)
        recipe11 = Recipe(title='Spaghetti Carbonara', image='', description='Not the spaghetti you\'re expecing.', chef_id=2)
        recipes.append(recipe11)
        recipe12 = Recipe(title='Gnocchi', image='', description='Gnocchi are small pieces of dough made with potatos, flour and eggs. They\'re chewy and absorb flavor so well, and is everybody\'s favorite!', chef_id=2)
        recipes.append(recipe12)
        recipe13 = Recipe(title='Omakase', image='', description='Joon used to work at the Michelin-starred Ju-Ni in NOPA, so he knows the right people with the right ingredients. He does a 13-course omakase, no substitutes allowed.', chef_id=3)
        recipes.append(recipe13)
        recipe14 = Recipe(title='Taiyaki', image='', description='Can\'t end a 13 course meal without some dessert! This snapper shaped waffle is a popular street food in Japan -- but don\'t worry, there\'s no fish in this, only a red bean filling.', chef_id=3)
        recipes.append(recipe14)
        recipe15 = Recipe(title='Tex Mex pizza', image='', description='', chef_id=4)
        recipes.append(recipe15)
        recipe16 = Recipe(title='Pecan Pie', image='', description='Everybody\'s new favorite pie flavor.', chef_id=4)
        recipes.append(recipe16)
        recipe17 = Recipe(title='Texas bbq', image='', description='Everything is slowly cooked and prepped at Tony\'s. He would usually bring sides like mac n cheese, main courses of ribs and brisket. It\s kind of like omakase but for beef.', chef_id=4)
        recipes.append(recipe12)
        recipe18 = Recipe(title='Beer', image='', description='Of course Tony brews his own IPA.', chef_id=4)
        recipes.append(recipe18)
        recipe19 = Recipe(title='', image='', description='', chef_id=4)
        recipes.append(recipe19)
        recipe20 = Recipe(title='Tandoori chicken', image='', description='This is a popular South Asian dish of chicken marinated in yogurt and spices. Served best with a side of naan and biryani!', chef_id=5)
        recipes.append(recipe20)
        recipe21 = Recipe(title='Garlic Naan', image='', description='Who knew you could make amazing naan in just a regular oven?', chef_id=5)
        recipes.append(recipe21)
        recipe22 = Recipe(title='Biryani', image='', description='Choose your protein and you will be amazed by what Anika has whipped up. Biryani is a layered Indian dish that includes rice, protein and vegetables, flavored by a variety of spices such as saffron and cardamom.', chef_id=5)
        recipes.append(recipe22)
        recipe23 = Recipe(title='Samosas', image='', description='Samosas are a fried pastry with a savoury potato filling, usually consumed at the start of a meal as an appetizer. Anika has spent many evenings as a child making these with her mom.', chef_id=5)
        recipes.append(recipe23)
        recipe24 = Recipe(title='Kalakand (Milk Cake)', image='', description='A popular Indian sweet made with ricotta cheese, sugar, dry milk powder, ghee and spices.', chef_id=5)
        recipes.append(recipe24)
        recipe25 = Recipe(title='Farmers Market Produce', image='', description='Anika will always make sure you end the meal with a beautiful assortment of the fresh goods she picked up from the farmer\'s market, or sometimes even her own home garden!', chef_id=5)
        recipes.append(recipe25)
        db.session.add_all(recipes)
        db.session.commit()

        # reviews = []
        # r1 = Review(user='', rating='♡♡♡♡', text='The food was so good! I took a star off because Diana was late.', chef_id=1, user_id=)
        # reviews.append(r1)
        # r2 = Review(user='', rating='♡♡♡♡♡', text='', chef_id=3, user_id=)
        # reviews.append(r2)
        # r3 = Review(user='', rating='♡♡♡♡', text='', chef_id=4, user_id=)
        # reviews.append(r3)
        # r4 = Review(user='', rating='♡♡♡♡♡', text='', chef_id=2, user_id=)
        # reviews.append(r4)
        # r5 = Review(user='', rating='♡♡', text='Diana was late.', chef_id=1, user_id=)
        # reviews.append(r5)
        # r6 = Review(user='', rating='♡♡♡♡♡', text='Anika is the best -- she's so warm and friendly, and she even made extra food for my friends who aren't super adventurous eaters.', chef_id=5, user_id=)
        # reviews.append(r6)
        # r7 = Review(user='', rating='♡♡', text='', chef_id=5, user_id=)
        # reviews.append(r7)
        # r8 = Review(user='', rating='♡♡♡♡', text='', chef_id=4, user_id=)
        # reviews.append(r8)
        # r9 = Review(user='', rating='♡♡♡♡♡', text='', chef_id=1, user_id=)
        # reviews.append(r9)
        # r10 = Review(user='', rating='♡♡♡♡♡', text='', chef_id=2, user_id=)
        # reviews.append(r10)
        # r11 = Review(user='', rating='♡♡♡♡', text='', chef_id=3, user_id=)
        # reviews.append(r11)
        # r12 = Review(user='', rating='♡♡♡', text='', chef_id=2, user_id=)
        # reviews.append(r12)
        # r13 = Review(user='', rating='♡♡♡♡', text='', chef_id=3, user_id=)
        # reviews.append(r13)
        # r14 = Review(user='', rating='♡♡♡', text='', chef_id=2, user_id=)
        # reviews.append(r14)
        # r15 = Review(user='', rating='♡♡♡♡', text='', chef_id=1, user_id=)
        # reviews.append(r15)
        # r16 = Review(user='', rating='♡♡♡♡', text='', chef_id=1, user_id=)
        # reviews.append(r16)
        # r17 = Review(user='', rating='♡♡♡♡', text='', chef_id=3, user_id=)
        # reviews.append(r17)
        # r18 = Review(user='', rating='♡♡♡♡♡', text='', chef_id=2, user_id=)
        # reviews.append(r18)
        # db.session.add_all(reviews)
        # db.session.commit()